# Generated by Django 3.1.7 on 2021-03-20 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('room', models.CharField(max_length=8)),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
                ('lecturer_username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='lecturer.lecturer')),
            ],
            options={
                'db_table': 'Event',
            },
        ),
    ]
