# Generated by Django 3.1.7 on 2021-03-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210320_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('building', models.CharField(max_length=64)),
                ('coordinates', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'Building',
            },
        ),
    ]
