# Generated by Django 3.1.7 on 2021-03-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20210326_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
    ]
