# Generated by Django 3.1.7 on 2021-03-20 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerLoginSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=32)),
                ('expires', models.DateTimeField()),
                ('lecturer_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturer.lecturer')),
            ],
            options={
                'db_table': 'LecturerLoginSession',
            },
        ),
    ]
