# Generated by Django 3.1.7 on 2021-03-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
