# Generated by Django 3.1.7 on 2021-03-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentloginsessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pass_hash',
            field=models.CharField(default='1234', max_length=128),
            preserve_default=False,
        ),
    ]
